### ISSUE TITLE
Updating Etsy Inventory Data from Gatsby

### ISSUE THREAD

**Issue by bathrobe** [dylanon/gatsby-source-etsy#16]
I'm curious if there's any methods in the plugin to send, say, PUT requests to the Etsy API if a product is bought on a Gatsby site. This might be a dumb question (I read Etsy's terms of service and couldn't tell if selling on a personal site with Etsy listings was not allowed).

Read the paragraph in the Gatsby docs several times and am still wondering how people imagine this working:

> Building your own site with Gatsby allows you to have the best of both worlds. You can take control over your customers’ experience and drive traffic to your own blazing fast website. You’re also able to avoid links to others’ listings competing for your customers’ attention. At the same time, you maintain all the benefits of having your products listed on Etsy.

Would the idea be to send traffic from etsy.com to a Gatsby-source-etsy'd site, then back to etsy.com for a checkout? Or could you feasibly build an independent ecommerce store on a Gatsby site with Etsy store data and sync the two of them with this plugin?

Thanks!

**Comment by dylanon** [comment]
As far as I know, the Etsy doesn't provide a way to purchase items via its API - This plugin only focuses on sourcing data from an Etsy during your Gatsby project build in order to showcase (and usually link to) items you have for sale on Etsy. I think the point the person who wrote those docs was trying to make is that by sending people to your website first to look at a product, you can limit competition for your customer's attention.

That being said, I just built this because I wanted to display a few listings on a website - Not really in the ecommerce game all that much!

**Comment by dylanon** [comment]
Just seeing now that your question was around syncing inventory - Short answer is, I'm not sure. Not really planning to add that functionality as this is a source plugin. You might be able to find an API client to handle that for you - perhaps [etsy-js](https://github.com/georgicodes/etsy-js).
